version: "3.8"
services: 
    react-web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /apps/node_modules
            - .:/apps
    react-test:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /apps/node_modules
            - .:/apps
        command: ["npm", "run", "test"]