version: "3.8"
services: 
    redis:
        image: "redis:latest"
    postgresName: 
        image: "postgres:latest"
        environment: 
            - POSTGRES_PASSWORD=password
    nginx:
        depends_on: 
            - api
            - client
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        restart: always
        ports: 
            - '3050:80'
    api:
        build: 
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /app/node_modules
            - ./server:/app
        environment: 
            - PG_USER=postgres
            - PG_HOST=postgresName
            - PG_DB=postgres
            - PG_PASSWORD=password
            - PG_PORT=5432
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    client:
        stdin_open: true
        build: 
            dockerfile: Dockerfile.dev
            context: ./frontend
        volumes: 
            - /app/node_modules
            - ./frontend:/app
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379