FROM node:alpine

WORKDIR /apps

COPY package.json .
RUN npm install

# this step is optional as in docker-compose we are already using docker volumes 
# to map our root to apps working directory

COPY . .

CMD [ "npm", "run", "start" ]